development:
  adapter: postgresql
  encoding: unicode
  database: nusantara2016_development
  pool: 5
  username: nusantara2016
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: nusantara2016_test
  pool: 5
  username: nusantara2016
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: nusantara2016_production
  pool: 5
  username: nusantara2016
  password:
